# Generated by Django 3.0.3 on 2020-02-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='hi',
            field=models.CharField(default='hi', max_length=200),
        ),
    ]
