# Generated by Django 3.0.3 on 2020-02-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_config_hi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='hi',
        ),
    ]
