# Generated by Django 3.0.3 on 2020-02-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_config_include_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'managed': False},
        ),
    ]
