# Generated by Django 3.0.3 on 2020-02-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_auto_20200225_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={},
        ),
    ]
