# Generated by Django 3.0.3 on 2020-02-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_auto_20200225_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='include_numbers',
        ),
        migrations.AddField(
            model_name='config',
            name='image',
            field=models.ImageField(default='templates/twitter-logo.jpg', upload_to=''),
        ),
    ]
