# Generated by Django 3.0.3 on 2020-03-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_remove_config_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='username',
            field=models.CharField(default='1mohammadjalali', max_length=200),
        ),
    ]
